# === Go ===
[[plugins]] # go support
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # go complete
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
on_ft = 'go'

# === Clang ===
[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp', 'cmake']
hook_add = 'source ~/dotfiles/.vim/rc/plugins/deoplete-clang.rc.vim'

# === Ruby / Rails ===
[[plugins]] # ruby support
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]] # ruby auto complete
repo = 'fishbullet/deoplete-ruby'
depends = ['deoplete.nvim']
on_ft = 'ruby'

[[plugins]]
repo = 'taichouchou2/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'romanvbabenko/rails.vim'
on_ft = 'ruby'


[[plugins]] # Rubyのメソッドの定義元にジャンプ
repo = 'szw/vim-tags'
on_ft = 'ruby'

[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = 'ruby'

# === Python support ===
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
hook_add = 'source ~/dotfiles/.vim/rc/plugins/vim-lsp-python.rc.vim'
on_ft = 'python'

# === HTML, scss, Haml, Slim ===
# HTML support
[[plugins]]
repo = 'othree/html5.vim'
hook_add = 'source ~/dotfiles/.vim/rc/plugins/html5.rc.vim'
on_ft = 'html'

# === Scss support ===
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

# === Haml support ===
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

# === Slim support ===
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# === YAML support ===
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yml'

# === JavaScript support ===
[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'javascript.jsx', 'jsx', 'vue']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
depends = ['deoplete.nvim']
hook_add = 'source ~/dotfiles/.vim/rc/plugins/deoplete-ternjs.rc.vim'
on_ft = ['javascript', 'javascript.jsx', 'jsx', 'vue']

#[[plugins]]
#repo = 'pangloss/vim-javascript'
#on_ft = 'javascript'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-javascript'
hook_add = 'source ~/dotfiles/.vim/rc/plugins/vim-lsp-javascript.rc.vim'
on_ft = ['javascript', 'javascript.jsx', 'vue']

[[plugins]] # jsx
repo = 'mxw/vim-jsx'
hook_source = 'let g:jsx_ext_required = 0'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

#[[plugins]]
#repo = 'othree/javascript-libraries-syntax.vim'
#on_ft = ['javascript', 'javascript.jsx']
#hook_source = 'source ~/dotfiles/.vim/rc/plugins/javascript-libraries-syntax.rc.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['html', 'javascript', 'vue']

[[plugins]] # json
repo = 'elzr/vim-json'
hook_source = 'let g:vim_json_syntax_conceal = 0'
on_ft = 'json'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# === markdown supports ===
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

# === Git Support ===
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/dotfiles/.vim/rc/plugins/vim-gitgutter.rc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-fugitive.git'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'gregsexton/gitv.git'

# === TeX support ===
# https://qiita.com/ssh0/items/4aea2d3849667717b36d
# https://qiita.com/ssh0/items/e6d7540cd46fac580bc2
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = 'source ~/dotfiles/.vim/rc/plugins/vimtex.rc.vim'

# === Satysfi support ===
[[plugins]]
repo = 'qnighy/satysfi.vim'
on_ft = 'saty'
